### ISSUE TITLE
Documentation Actions Point to Vector

### ISSUE THREAD

**Issue by T00mm** [excaliburjs/Excalibur#1049]
The current docs at https://excaliburjs.com/docs/api/v0.18.0/classes/_actions_actioncontext_.actioncontext.html still talk about ex.Point which doesn't exist anymore. This should be ex.Vector

**Comment by T00mm** [comment]
Side-comment, is it also possible to add GIF/MP4 to demonstrate code? How would this work? 

[Example video](https://giphy.com/gifs/5e21urLNSMJPazbKKj/html5)

1. Is this allowed?
2. Do we host it on Github or other external websites like Gyphly?
3. Is this something you would love to have?

**Comment by kamranayub** [comment]
I like the idea of videos but it depends on what they're on. I'll have to
watch your video later. I think ideally we hoped we can start to add new
user docs (see PR open in excaliburjs.github.io) that contain full examples
that get compiled on build and embedded on the page, perhaps through
codesandbox or some other online project host (Glitch). Even cooler if we
write BrowserStack tests for them that run and notify us if they break.

Videos I'd see being good on "recipe" docs or "heres how to do X with
Excalibur" and then hosting on YouTube and embedding/linking. I've also
been throwing around eventually doing videos on Egghead for Excalibur.

The main issue right now is we haven't hit v1 yet because we plan to make
wider API changes that, if we made tons of docs/videos, would need to be
heavily updated. The compiled code samples would at least give us more
useful user docs and at the same time force us to ensure they're kept
updated.

**Comment by T00mm** [comment]
Good point, would be stupid to redo everything indeed.

To clarify for other readers, kamranayub is talking about https://github.com/excaliburjs/excaliburjs.github.io which is the website repo (different from this one)

I am very interested in giving feedback for this exercise and do believe in making test units for the documentation website. Maybe we should move this discussion to that repo?

**Comment by kamranayub** [comment]
Yeah would love it! There may be an issue already otherwise feel free to
create one!
