### ISSUE TITLE
[chore] Upgrade Excalibur to TypeScript v3.x

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#1052]
### Context
It's good to keep up with TypeScript, it gives us stronger ability to reason about types, and new language features to take advantage of.

Depedencies:

- [ ] Ensure that typedoc (our documentation generator is compatible
- [ ] Ensure that excalibur plugins still work with excalibur

### Proposal
- [ ] Upgrade to the latest version of TypeScript
- [ ] Fix any compilation errors
- [ ] Update samples/docs if needed

**Comment by atanasbozhkov** [comment]
This looks interesting. I have done a similar upgrade already for another project and I would be interested in doing this one for Excalibur.
I am not sure how to test the plugin system though. If you can give me some rough guidance I should be able to figure it out.

I've got a branch up with the changes I've made so far - [Compare Branches](https://github.com/excaliburjs/Excalibur/compare/master...atanasbozhkov:feature/typescript-3)

Notes:
- Had to to a (as any) on `window.document` reference when checking for legacy browser compatibility since typescript 3 yells at you when you try to access a depricated property.
- Changed a couple of types to match more closely what TS expects them to be (a minor typo was present) 
- Typedoc required an upgrade to 0.13.0 to support typecript 3.1 properly. I ran it before and after the upgrade and compared the results. The differneces seem minor and all relating to blob references or whitespecing. Typedoc still warns about a reference in the docs in IAudioImplementation. I believe it present in the current docs as well. Might be worth fixing that as well.

> Warning: [MarkedLinksPlugin]: Found invalid symbol reference(s) in JSDocs, they will not render as links in the generated documentation.
>   In "Interfaces/IAudioImplementation".IAudioImplementation: [[AudioTag]]

- When doing an `npm install`  a new warning appears about peer depedencies of Karma. Tests run fine and there doesn't seem to be anything broken. No new version of `karma-typescirpt` is out to support this as of yet.

> npm WARN karma-typescript@3.0.13 requires a peer of typescript@2 but none is installed. You must install peer dependencies yourself.

Thanks, 
Nasco

**Comment by eonarheim** [comment]
@atanasbozhkov Excellent, go for it!

The plugins have the form `excalibur-{name}`
 * excalibur-tiled is the biggest one to check https://github.com/excaliburjs/excalibur-tiled
 * excalibur-pack hasn't been touched in a while and may be out of scope 
 depending on the level of effort https://github.com/excaliburjs/excalibur-pack

The key example to check is https://github.com/excaliburjs/example-ts-webpack, the others haven't been touched in a while and may require more effort than we want to spend right now to upgrade to typescript@3, until we have a better way of keeping them in sync with the latest changes in main Excalibur. 

@atanasbozhkov We'd be open to any suggestions you have in this area, but we are planning to update our CI process to check Excalibur master against all our plugins/examples which will be a large effort and probably something a core member will have to do needing access to the CI system.

**Testing the plugins/examples** will involve upgrading their references to excalibur (probably using npm link or using npm pack and installing the tar.gz directly) the npm pack method has been the most successful for me.

Typos and broken typedoc links are definitely fair game to fix.

I'd be okay without a new `karma-typescript` for now, as long as everything stays roughly backwards compatible between typescript@3 and typescript@2 in Excalibur. And it looks like they have something in the works regarding typescript support for v4 https://github.com/monounity/karma-typescript/issues/298 so we can **open an issue to follow up once v4 is released.**

**Comment by eonarheim** [comment]
@atanasbozhkov Any interest in continuing this work?
