### ISSUE TITLE
Bug on sprites with scene

### ISSUE THREAD

**Issue by Chklang** [excaliburjs/Excalibur#1062]
Hi

When i want to use scenes, sprites aren't drawn. I've created a JSFiddle exemple : https://jsfiddle.net/Chklang/pvx6wm5f/3/

Regards.

**Comment by kamranayub** [comment]
Hi @Chklang,

We're happy to help! In the future, we just would recommend asking first [on the group](https://groups.google.com/forum/#!forum/excaliburjs) so that if there ends up not being a bug, we don't have extraneous issues.

For your example, the issue appears to be trying to call `goToScene` without waiting until the game has loaded fully.

I changed your Fiddle slightly and now it works: https://jsfiddle.net/pvx6wm5f/4/

In general, the pattern we recommend is to run all game init logic after waiting for the `game.start` Promise to return.

```ts
const game = new Engine(...);
const loader = new Loader(...);
game.start(loader).then(() => {
  // Everything else
});
```

It would be nice I think looking at this for us to warn/throw if you try to use the game without waiting for it to start. I'll create a separate issue for that.

If this helps answer your question, go ahead and close the issue.

**Comment by Chklang** [comment]
Great!!! Thanks for your correction. I think that the exemple https://excaliburjs.com/docs/api/edge/classes/_scene_.scene.html must be updated.

ps  : Ok, i've keep the google group url :)

**Comment by kamranayub** [comment]
Thanks I'll make a note to update those docs when I migrate them!
