### ISSUE TITLE
ex.Color.Black.lighten() does not work

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#1084]
### Steps to Reproduce
See codepen
https://codepen.io/eonarheim/pen/BvORaG?editors=0010#0

```
let newColor = ex.Color.Black.lighten();
expect(newColor.r).not.toEqual(ex.Color.Black.r);
expect(newColor.g).not.toEqual(ex.Color.Black.g);
expect(newColor.b).not.toEqual(ex.Color.Black.b);
```
Looks like this issue is right here, it is using multiplication. When the black it is `0` so multiplication will always yeild a `0`

### Expected Result
The new color should be lighter than black

### Actual Result
New color is still black

### Environment

- browsers and versions: N/A
- operating system: N/A
- Excalibur versions: master

### Current Workaround
None

**Comment by Carghaez** [comment]
What result do you expect from lighten, for example by 50%, a black color?

The problem is given by the fact that in general 50% lighten of a color mean add a 50% of white and not from the same color. So the correct algorithm should be:

``` Javascript
    var temp = new Color(this.r, this.g, this.b, this.a);
    temp.r = temp.r * (1 - factor) + Color.White.r * factor;
    temp.g = temp.g * (1 - factor) + Color.White.g * factor;
    temp.b = temp.b * (1 - factor) + Color.White.b * factor;
```
Or more simply:

``` Javascript
    var temp = HSLColor.fromRGBA(this.r, this.g, this.b, this.a);
    temp.l += (1 - temp.l) * factor;
    return temp.toRGBA();
```

That means if we have HSL(100, 20, 40), from a lighten function of 50% we have a result of HSL(100, 20, 70) and not HSL(100, 20, 60).

If you agree with that I can submit a pull request with test units.

I also notice that a 'src/spec/images/SpriteSpec/icon-lightened.png' image had applied a wrong lighten algorithm.

**Comment by eonarheim** [comment]
Hi @Carghaez this sounds very reasonable, please continue with the proposed solution.
