### ISSUE TITLE
Add flag to IEngineOptions to set canvas transparency

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#1096]
### Context
Currently excalibur does not expose a way to enable/disable canvas transparency, see https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Optimizing_canvas#Turn_off_transparency.

We can save some processing by defaulting to a non-transparent canvas (which is a rare case)

### Proposal
* [ ] Add an additional property to `IEngineOptions` called `enableCanvasTransparency` that will can enable/disable canvas transparency
* [ ] Default excalibur's canvas context to NOT be transparent by default when creating the graphics context `canvas.getContext('2d', { alpha: false });`

**Comment by edualb** [comment]
Hello,  i get this issue, but I can not create tests. Have something wrong with my test code, can you(@eonarheim)  help me pls?

[051b0ef](https://github.com/edualb/Excalibur/commit/56a10e2e038061f5cdf22e6b2eb0999b94d906f4)

**Comment by jedeen** [comment]
Hello! Thanks for contributing! We'll take a look at your fork and get back to you within the next day!

**Comment by jedeen** [comment]
Hello @edualb!

At least initially, disabling the canvas transparency by default is causing failures in some of our existing tests (image-matching) because canvas transparency was not disabled when they were configured. We can adjust those tests to account for the change.

Please open a pull request for your changes so we can continue to work with you and provide better visibility. Thanks!
