### ISSUE TITLE
Physics on Different Framerates

### ISSUE THREAD

**Issue by ColeyG** [excaliburjs/Excalibur#1130]
Hi, I was testing the engine on my linux machine, but when swapping to a different (more powerful) machine, I noticed that the physics were floatier and my characters slicker. This is weird since in my game the characters can jump higher and move faster with a higher framerate.

### Steps to Reproduce
Create a game in a slow framerate environment, then test it somewhere with high performance.

### Expected Result
Physics should still resolve similarly, instead of producing different results.

### Actual Result
Characters jumped higher, moved faster, and acted odd.

### Environment
- browsers and versions: Electron (Latest Release)
- operating system: Ubuntu/Windows
- Excalibur versions: 0.22

### Current Workaround
None

**Comment by eonarheim** [comment]
@ColeyG Thanks for opening and issue!

The `update` method is called once per frame, given the [implemenation](https://github.com/ColeyG/items-on/blob/master/game/player.js#L11-L26) `this.velY--` will be called less frequently on a lower framerate than a higher one, decreasing velocity slower than a higher framerate.

The trick is to scale your `update` method with delta, so that update distance/velocities are consistent given different frame rates. Delta provides the time it took to render the previous frame in milliseconds.

Here is an example of scaling by delta:

```javascript
//
// This implementation imparts acceleration (change in velocity) every update, meaning the longer a key is pressed the faster the character will move.
//
update(engine, delta) {
    let seconds = delta/1000; // convert from milliseconds to seconds
    let accel = 2; // 2 pixels/sec/sec
    ex.Actor.prototype.update.call(this, engine, delta);
    if (engine.input.keyboard.isHeld(ex.Input.Keys.W)) {
        this.velY = this.velY - accel * seconds;
    }
    if (engine.input.keyboard.isHeld(ex.Input.Keys.A)) {
        this.velX = this.velX  - accel * seconds;
    }
    if (engine.input.keyboard.isHeld(ex.Input.Keys.S)) {
        this.velY = this.velY + accel * seconds;
    }
    if (engine.input.keyboard.isHeld(ex.Input.Keys.D)) {
        this.velX = this.velX + accel * seconds;
    }
    this.x = this.x + this.velX;
    this.y = this.y + this.velY;
}
```

**Comment by eonarheim** [comment]
@ColeyG If you have any more questions, feel free to ask them in the forum
