### ISSUE TITLE
PointerDragMove event always binds to first actor initialized

### ISSUE THREAD

**Issue by HParker** [excaliburjs/Excalibur#1191]
### Steps to Reproduce
```typescript
class Game extends ex.Engine {
  constructor() {
    super({
      width: 600,
      height: 600,
      displayMode: ex.DisplayMode.Fixed,
    });
  }

  public start(loader?: ex.Loader) {
    return super.start(loader);
  }
}

class TestBlock extends ex.Actor {
  constructor(x: number, y: number) {
    super({
      pos: new ex.Vector(x, y),
      height: 100,
      width: 100,
      color: ex.Color.Red,
    })
    this.on(ex.EventTypes.PointerDragStart, (event) => {
      this.color = ex.Color.Black;
    });
    this.on(ex.EventTypes.PointerDragEnd, (event) => {
      this.color = ex.Color.Green;
    });
    this.on(ex.EventTypes.PointerDragMove, (event) => {
      this.color = ex.Color.Yellow;
    });
  }
}

const game = new Game();

const testBlockOne = new TestBlock(150, 100);
const testBlockTwo = new TestBlock(450, 100);

game.add(testBlockOne)
game.add(testBlockTwo)

game.start();
```

### Expected Result
Actor being dragged would turn black then yellow, then green.
![correct-behavior-draging](https://user-images.githubusercontent.com/4482399/60302829-b734bf00-98e9-11e9-8ae4-5ac31dea8cfa.gif)

### Actual Result
When dragging on the second object that was initialized, the second object turns black, the first object turns yellow and finally the second object turns green.
![incorrect-behavior-draging](https://user-images.githubusercontent.com/4482399/60302883-dc293200-98e9-11e9-95ed-93a61a2ef603.gif)

### Environment
Chrome 75.0.3770.100
- browsers and versions: Chrome 75.0.3770.100
- operating system: MacOS Mojave 10.14.5
- Excalibur versions: 0.23.0
- Started from https://github.com/excaliburjs/example-ts-webpack and replaced the `index.ts` file with the code above.

### Current Workaround
Unknown

**Comment by HParker** [comment]
Possible helpful information: 
- PR introducing dragging: https://github.com/excaliburjs/Excalibur/pull/933
- Removing the `on` calls from the constructor does not change the behavior
- logging `this` from the `EventTypes.PointerDragMove` callback always returns object with id 0.
- the callback in `PointerDragMove` is aware that the object is not under the cursor, but still emits the event for it.
I really can't figure out what makes the drag move event different.
Event is emitted here: https://github.com/excaliburjs/Excalibur/blob/v0.23.0/src/engine/Input/Pointer.ts#L258 and looks exactly like how the `pointerdragstart` event is emitted: https://github.com/excaliburjs/Excalibur/blob/v0.23.0/src/engine/Input/Pointer.ts#L199

**Comment by eonarheim** [comment]
@HParker Good find, that is really odd. This will need some investigation, I can't tell why either.

**Comment by HParker** [comment]
@eonarheim Thanks for the quick response! Yeah, I'll keep looking as well. 

I am trying to understand the eventing system a bit especially as it relates to actor events. My only theory right now is that the actor that gets called in the `Pointer.ts` code that emits the events just isn't getting all the actors and is just getting the first one.

That idea lead me back to this code: https://github.com/excaliburjs/Excalibur/blob/ce1c19d86b281d6c024f6e846fb809958facf9ce/src/engine/Events.ts#L206
It looks promising since it is only talking about emitting events for one actor, but I am lost trying to understand what `eventPath` on `GameEvent` is. 

It is totally possible I am going down the wrong path though.

**Comment by eonarheim** [comment]
@HParker it is very confusing, I spent a good chunk of today deciphering it :(

I think your intuition on `eventPath` is right on the money, I think the bug is that `eventPath` is shared mutable state and is getting mangled. `Pointer` seems to have the right `actorsUnderPointer` recorded, but at the time of dispatch `eventPath` does not match this causing a dispatch to the wrong actor.

The way I understand the pointer system now is the following:
1. The `Pointers` type is responsible for collection up native browser pointer/mouse/touch events
2. For each pointer (it supports multiple pointers) an Excalibur pointer event is manufactured and stored
3. Once per frame during update, these pointer events are "propagated" to any actors it thinks needs the events, problem is that `eventPath` is different per actor and pollutes the pointer event instance as it's being distributed.

A refactor to a more "functional" stateless way of operation I think will clear this up, changing step 3 to calculate the actors under each pointer and propagate to those actors only, potentially re-think `eventPath` or re-calculate it per dispatch and remove it from the base `GameEvent` type, currently it is only a concern of pointer events.

/cc @kamranayub Any suggestions or corrections?
