### ISSUE TITLE
Upgrade Jasmine testing framework to 2.4

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#126]
- [x] Remove `grunt-jasmine-node`
- [x] Remove `jasmine-node`
- [x] Install dependency on `jasmine-npm` package
- [x] Create a `jasmine.json` config
- [x] Call jasmine from grunt task
- [x] Ensure istanbul still works

https://github.com/jasmine/jasmine-npm
http://jasmine.github.io/2.4/node.html

**Comment by kamranayub** [comment]
I'm going to recommend we remove dependency on grunt-jasmine-node and jasmine-node and instead switch to OFFICIAL `jasmine-npm` package:

https://github.com/jasmine/jasmine-npm

Then we'll just call it manually using grunt since it just is a command that consumes a jasmine JSON config.

http://jasmine.github.io/2.4/node.html
