### ISSUE TITLE
Investigate parsing GIFs to ex Animations

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#153]
There are a lot of animation assets that would nice to use natively in ex without unpacking the gif into a spritesheet.

**Comment by kevin192291** [comment]
What is the progress on this issue? If no one is actively working on it. I would be happy to pick it up.

**Comment by eonarheim** [comment]
Hi @kevin192291 this would be great! I'll assign myself so no one takes the issue.

I'd look into how gifs are packed together natively, build something in Excalibur to parse the native format into RGB image frames, and extract them into a SpriteSheet. 

It may also be useful to allow excalibur users to specify a color to be transparent (I believe gifs do not support transparency).

**Comment by kevin192291** [comment]
Quick update on my progress:
I have started to prototype a way to split Gifs into separate frames, here is my attempt:
[https://stackblitz.com/edit/gif-frame-parser](https://stackblitz.com/edit/gif-frame-parser)
I now am going to try to work in the efficiency of it. I am concerned about how GIFs work though. Some GIFs (depending on how they were made) will store the deltas of the changes between frames for efficiency, this is not handled here. See my light example GIF link in the stack blitz.
I will now attempt to add it to a fork of the Excalibur repo, I am wondering what you think of the progress and if you have any suggestions or comments.

**Comment by eonarheim** [comment]
@kevin192291 This is fantastic! I think you are on the right track. We probably do want to handle the case where only deltas are stored, is there a binary header that indicates the type? or is data inspection necessary to detect these?

I think putting this logic into a new resource type like `Texture` might be the way to go to integrate this work into Excalibur. 

Base resource: https://github.com/excaliburjs/Excalibur/blob/master/src/engine/Resources/Resource.ts

Maybe `GifAnimation` or maybe just `Gif`? I'm open to a better name.

Possible api
```typescript
let gif = new Gif('https://path/to/my/gif');

// after loading the Gif resource
let anim = gif.getAnimation() // fully built ex.Animation
let spriteSheet = gif.getSpriteSheet() // fully built ex.SpriteSheet
let tex = gif.getTexture() // ex.Texture backing image bitmap
```

**Comment by kevin192291** [comment]
Hello, I have made more progress.
I created a Gif object along side of the Texture object.
I have added some code in Texture to allow Texture to build an image from a data url.
The current problem is that the sprite that is generated from the texture when calling .asSprite()
has a canvas size of 0. I have not found a solution yet, would anyone have a quick moment to have a look? Once this is done, I can finish building the sprite sheet and finally the animation.

**Comment by kevin192291** [comment]
Hello! More good news, I have finished importing the code to my fork. Before I start work on making the code more typescripty and adding docs/tests I am wondering if anyone is up for taking a quick look at what I have been up to?
My fork is at: [https://github.com/kevin192291/Excalibur](https://github.com/kevin192291/Excalibur)

I can change the function names, but at the moment I have:
`var gif = new ex.Gif('sword.gif', ex.Color.Black); // param1: gif path, param2: transparent color (maybe make this an array?);
gif.asAnimation(game, 500); // return an ex.Animation;
gif.asSprite(0); // Get the 0th frame of the sprite;
gif.asSpriteSheet(); // Get the spritesheet;
`
The reason I went with as<Something> instead of get<Something> was to stay consistent with the texture's asSprite() method, but if you want to change it to Get, that is no problem at all.
What do you think of how this is coming along?

Thanks!

**Comment by eonarheim** [comment]
Hi @kevin192291 

You're fork is looking great! The team will be able do a more thorough code review once you've opened a PR.

I agree I like staying consistent with `asSprite` naming convention with `asAnimation` and `asSpriteSheet` makes sense to me.

Only question I have is about these dependencies in the `package.json`, they don't appear to be used?

```
"dependencies": {
    "@types/jdataview": "0.0.30",
    "gif-frames": "^1.0.0",
    "jdataview": "^2.5.0"
  }
``
