### ISSUE TITLE
How can I color a Sprite in version 0.25.x?

### ISSUE THREAD

**Issue by Mytrill** [excaliburjs/Excalibur#2267]
I cannot find any documentation/example on how to apply a color to a sprite.
It seems there used to be some Effect that could be added to sprites before (https://excaliburjs.com/docs/api/edge/classes/LegacyDrawing.Sprite.html#effects) but I cannot find any similar API in the latest version, I also checked the Migrating section in the docs (https://excaliburjs.com/docs/migration) but there is no mention of it there either.

Thank you!

**Comment by eonarheim** [comment]
Hi @Mytrill 


You are correct there isn't anything in the newer API to apply a color to the pixels in a graphic. I've been thinking about building something to provide a similar feature in the newer API.

If I can ask, what is your use case? It will help inform any future API updates/docs/workarounds.

One low fidelity workaround at the moment might be to update the image source to alter the color in an image editor.

Otherwise it might be possible to use the ex.Canvas or a custom ex.Raster implementation to change the color of pixels on the fly (I'm away from a machine for a few days, but I'll see if I can come up with something)

@kamranayub @jedeen Let me know if you have some ideas
