### ISSUE TITLE
Jumping against and over a wall sometimes causes a collision that resets velocity (Arcade Physics)

### ISSUE THREAD

**Issue by mattjennings** [excaliburjs/Excalibur#2343]
![Kapture 2022-06-06 at 16 58 07](https://user-images.githubusercontent.com/8703090/172256272-d8bce343-b63c-44eb-ac7d-3fc25f5c12f6.gif)

### Steps to Reproduce

The above gif can be reproduced using this [CodeSandbox example](https://codesandbox.io/s/excalibur-jump-along-wall-bug-xsym4w?file=/src/index.js). (CodeSandbox is finicky with capturing key events, best to open the preview in a separate window).

Try moving the player to the right against the wall by holding the right arrow key. While still holding right, hit up to jump. Sometimes the player will slide along & above the wall, but other times it will "snap" to the top of the wall.

### Expected Result

The player should slide along & above the wall

### Actual Result

The player snaps to the top of the wall instead and velocity is reset - sometimes.

### Environment

- browsers and versions: Chrome 102, Safari 15.5 
- operating system: macOS 12.4 
- Excalibur versions: 0.26, 0.25, didn't try anything earlier 
- Using a macbook pro with 120hz screen incase that has an impact on the physics tick rate

### Current Workaround

None that I know of. I'm still quite new to using Excalibur, but this movement logic was taken from the Sample Platformer, so let me know if there's a better way to be applying velocities/collisions that might remedy this.

**Comment by eonarheim** [comment]
I mentioned in #2344 but I think these might be related.

I'm thinking a collision resolution bias towards vertical or horizontal collisions might help? Otherwise we may want to re-think the velocity solve step in the `ArcadeSolver` or perhaps make it configurable to be more forgiving on corner collisions such that if there is no clear correct vertical/horizontal direction to bias either horizontally or vertically.

<img width="685" alt="image" src="https://user-images.githubusercontent.com/612071/172267705-53fac84e-1d03-4756-8004-7ede2f310fba.png">

**Comment by eonarheim** [comment]
Okay an additional tweak was made to fix this, effectively we don't adjust any velocities if the colliders are already moving away from the contact.

<img width="405" alt="image" src="https://user-images.githubusercontent.com/612071/172495189-4c316536-b0a3-40e0-841f-72d1593a2bd9.png">

This makes platforms a bit more forgiving on corner when rolling off and jump up and around.

![cancel-velocity-fix](https://user-images.githubusercontent.com/612071/172500318-539f3a36-31ae-4efc-b6ab-c4524b297adb.gif)
