### ISSUE TITLE
Some links appear to be broken on docs

### ISSUE THREAD

**Issue by mattjennings** [excaliburjs/Excalibur#2398]
for example:

https://excaliburjs.com/docs/entity-component-system
https://excaliburjs.com/docs/actors

Any of the `[[text]]` links are being shown literally.

I think this happened fairly recently, or at least I don't recall the links being broken a week or 2 ago.

**Comment by eonarheim** [comment]
@mattjennings Hmm, it might have been the TypeScript upgrade on main, TypeDoc is really picky about that unfortunately. I'll take a look.

**Comment by eonarheim** [comment]
@mattjennings Thanks for pointing this out! It was the TypeScript upgrade in combination with TypeDoc

Fixed with https://github.com/excaliburjs/Excalibur/commit/48471a77a2cae3e7b78447a8c54102b0844d7839 and https://github.com/excaliburjs/excaliburjs.github.io/commit/997069d0f6885ad8661276762fc95f7ad7cae02a
