### ISSUE TITLE
Investigate Unintended Screenshot Antialiasing 

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#2421]
### Steps to Reproduce

See discussion thread: https://github.com/excaliburjs/Excalibur/discussions/2415

Excalibur screen shots seem to apply an AA effect that wasn't present on the game screen at the time the screenshot is taken.

Before screenshot, crisp pixels

<img width="190" alt="image" src="https://user-images.githubusercontent.com/612071/179406002-9df718c7-7ed4-482a-b028-e4ae0a799407.png">

After screenshot, some unexpected AA effect.

<img width="206" alt="image" src="https://user-images.githubusercontent.com/612071/179406021-3a296e1b-7c46-4f2b-b9bf-5078c38ac4c5.png">

Seems to only affect the moving Actor in this example?

### Expected Result

The screenshot should look exactly like the frame as it was displayed, including any relevant AA settings.

### Actual Result

Some unintended AA is being applied.

### Environment

- browsers and versions: Chrome 103
- operating system: Win
- Excalibur versions: 0.27.0

### Current Workaround

None

**Comment by mattjennings** [comment]
Here's a repro: https://codesandbox.io/s/excalibur-antialias-screenshot-zbw94v

At the bottom you'll see `new ScreenShotter({ hires: false })` - changing that to true will fix the antialiasing. I think this is _probably_ not a bug though. It only happens if the character is on a half-pixel. If `engine.screenshot(false)` produces a screenshot at game resolution, then it makes sense that it gets antialiased.

The workaround is to take the screenshot at hires so it matches the canvas resolution, but you just have to do a bit of extra work when drawing to scale it back down according to `window.devicePixelRatio` (as shown in the repro).

Anyway, all that to say I _don't think_ there's anything to do here, I just hit an edge case with an acceptable workaround.

**Comment by eonarheim** [comment]
@mattjennings I've found that matching the internal screenshot canvas to the current screen smoothing seems to produce more desirable results out of the box (https://github.com/excaliburjs/Excalibur/pull/2428). I think this makes the workaround unnecessary? 

Let me know what you think! I'm still poking around, it is also resisting being tested for some reason

**Comment by mattjennings** [comment]
@eonarheim oh! very interesting. I just gave it a try and I'm not seeing any antialiasing like before, so I would say this is a good fix!

**Comment by eonarheim** [comment]
Thanks for checking it out! I'll have some time today to hopefully get it merged 👍
