### ISSUE TITLE
Unexpected intersection values in precollision event

### ISSUE THREAD

**Issue by mattjennings** [excaliburjs/Excalibur#2488]
I apologize for the vague title, but I'm not too sure how to succinctly explain this one 😅

Below is a clip of logging `ev.intersection` in the `precollision` event for the red actor. It has a passive collider, while the green walls are fixed. It seems that when the red actor is colliding near the bottom 10% of the green actor, the intersection stops populating `x` and instead populates `y`.

(the laggy console logging is just codesandbox being slow)

https://user-images.githubusercontent.com/8703090/188290360-01a15255-5a2d-4915-84e0-66100099d322.mp4

Here's a bit more context showing how I initially ran into this:

<img width="195" alt="CleanShot 2022-09-03 at 18 30 45@2x" src="https://user-images.githubusercontent.com/8703090/188290579-8eacc52b-6536-4385-b6e0-9a47da7bdf23.png">

This is essentially a makeshift raycast.  There are 8 of these "rays", one on for each corner, doing the same `precollision` event checking. For debugging purposes, when any of them detect a precollision they are colored red. I then use the `intersection` values to determine the distance to the collision. So the horizontal colliders will use `x`, and vertical `y`. As you can see, the horizontal bottom-right corner suffers from this issue, as the `x` value is 0 for its intersection.

It's possible I am abusing this intersection value for something it's not meant to be used for. #2410 is likely going to be the better solution... but this is actually working quite well otherwise! 

Is there a reason only `x` or `y` are populated, and not both? Perhaps it would be better if they were?

### Steps to Reproduce

https://codesandbox.io/s/excalibur-collision-intersection-bug-x26fug?file=/index.js

### Expected Result

The `x` value of the intersection should continue to be the populated value.

### Actual Result

The `x` value stops being populated and instead `y` is.

### Environment

- browsers and versions: Chrome 105
- operating system: macOS 12.5
- Excalibur versions: 0.27

**Comment by eonarheim** [comment]
@mattjennings Definitely seems like a bug to me, very unexpected.

I'll dig in and see if I can figure out what's up. 

Sorry for the rough edges in collision, but I appreciate all the fixes we've got into excalibur because of your efforts 👍

**Comment by mattjennings** [comment]
@eonarheim no worries at all! It overall has been working very nicely for me and I'm happy to help iron out some of these edge cases.

**Comment by eonarheim** [comment]
Hi @mattjennings 

I think I understand what's happening, the collision machinery is picking the shortest distance to resolve interpenetration between the two shapes. Technically moving the shape in the y-direction at the point in the reproduction is the shortest distance to resolve the interpenetration (but it definitely seems unexpected when treating the collider like a ray).

One possible workaround is to make the walls a little taller (might not be possible in your application)

<img width="360" alt="image" src="https://user-images.githubusercontent.com/612071/188513424-0149f79a-c925-4bda-bc6c-43d69c17c89b.png">

Another workaround might be to make the collider acting as a "ray" shorter, but you'll still have the problem (only less noticeable) at the extremes of walls unless you oversize them vertically.

> Is there a reason only x or y are populated, and not both? Perhaps it would be better if they were?

This is a good question, mostly because it's oriented towards the shortest distance to resolve interpenetration. Only one direction X/Y can be the shortest when oriented orthogonally. 

Although I agree it would be useful to know both the shortest X and Y direction to resolve interpenetration when orthogonally oriented... I'll noodle on possibilities. Perhaps raycasting is the way to solve this use case generally, but I'm not sure yet.

**Comment by mattjennings** [comment]
@eonarheim hmm I see... I think I understand. Unfortunately the suggested workarounds aren't going to work for me but I know I'm sort of pushing the boundaries of this approach anyway. I can wait for the raycasting and see how well that works in its place!

**Comment by eonarheim** [comment]
Hopefully I can get that raycasting finished up this week 👍

**Comment by mattjennings** [comment]
@eonarheim finally got around to playing with the raycasting. So far it's working _much_ better than my makeshift raycasting, so I think it will the proper tool for my usecase.

As for this particular bug, I'm not sure if you think there's a need to improve anything here, so I'll leave it up to you whether or not to close this issue. For measuring distance to collision, raycasting is definitely the way to go.

**Comment by eonarheim** [comment]
Thanks @mattjennings! Good to hear! Let me know if anything comes up with the new raycasting 👍
