### ISSUE TITLE
Bug with custom build: Circular Dependency Causes `Actor` to be `undefined` in `ParticleEmitter`

### ISSUE THREAD

**Issue by JumpLink** [excaliburjs/Excalibur#3055]
### Description
I am using TypeScript source files directly from Excalibur.js instead of the bundle for several advantages:
- Better source maps as my project directly uses the sources, it can generate better source maps.
- I can decide for myself which target (e.g. ESNext, ESM, ...) I want to use
- Ability to make changes without needing to rebuild Excalibur with fast page reload.
- Direct access to the source code in my IDE.
- Faster builds with esbuild (or possibly vite, which also utilizes esbuild) which is significantly faster than Excalibur’s webpack.

This approach has been working well until a recent issue where `Actor` is `undefined` when referenced in the `ParticleEmitter` class definition. This seems to be due to circular dependencies and import order issues, causing `Actor` to be undefined when `ParticleEmitter` tries to extend it in my own bundled file.

I understand if this is not recognised as a bug as this is a very specific problem, I am happy to fix it myself and hope it is accepted.

### Steps to Reproduce

Build Excalibur with Vite or ESBuild with a small sample game, this needs configurations so that this also works with the imported `*.css` and `.glsl` files because vite needs to import them using a `?raw` prefix by default like this:

```ts
import lineVertexSource from './line-vertex.glsl?raw';
```

I can create an working example using esbuild or vite if there is a need for it.

### Expected Result

`ParticleEmitter` should successfully extend `Actor` without encountering an undefined issue.

### Actual Result

The `Actor` class is `undefined` when `ParticleEmitter` attempts to extend it, due to circular dependencies and import order issues within the TypeScript source files.

### Environment

- Excalibur versions: latest main branch
- Build tools: esbuild/vite (latest versions)

### Current Workaround

Just use the official bundle instead of the sources directly as intended.

**Comment by eonarheim** [comment]
@JumpLink thanks for the fix, I'll gladly accept this one! This actually bit me in the wallaby config and I didn't dig into the cause.

We'll probably stick to webpack for the core repo for a while because of the control it gives over compilation and the ability to pull in non-js files into the bundle easily. However, I totally understand the desire for increase speed when iterating like you are in a game (I use vite/parcel when building games usually).

In other news I'm working on GPU based particles for the next version 🤞 hopefully I get them completed soon! https://eonarheim.github.io/webgl-particles/ We should be able to render very large numbers of particles and have them collide with a mask!
