### ISSUE TITLE
The events for some gamepad buttons do not work.

### ISSUE THREAD

**Issue by hanekoo** [excaliburjs/Excalibur#3317]
In Chrome, the gamepad is recognized with 18 buttons, but the GamepadButtonEvent.Buttons only provides 16 buttons, and the additional two buttons do not trigger events. How can I get events for all the buttons?

**Comment by eonarheim** [comment]
@hanekoo Good question! Out of curiosity what gamepad hardware are you using? I want to make sure we add these buttons to excalibur

I think this is a limitation of the current Excalibur implementation, it can't read past 16 without some modification. You might be able to patch the `ex.Buttons` enum to add the additional numeric values and it might just work.... https://github.com/excaliburjs/Excalibur/blob/main/src/engine/Input/Gamepad.ts#L415

Otherwise I think you might have to reach into the native js gamepad until we fix this in Excalibur. MDN has some good docs here https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API

`navigator.getGamepads()`

**Comment by hanekoo** [comment]
Thank you for your reply. 

I am using a Nintendo Pro controller, and the Home (index 16) and Screenshot (index 17) buttons are missing. 

Here are some documents you can refer to：
- [sdl2 controller buttons enum](https://wiki.libsdl.org/SDL2/SDL_GameControllerButton)
- [standard gamepad mapping](https://w3c.github.io/gamepad/#dfn-standard-gamepad)

I believe the GamepadButtonEvent should provide the button indices from the Gamepad API instead of filtering them out. This would allow for more extensibility and flexibility.

**Comment by eonarheim** [comment]
@hanekoo Awesome, thanks for the info. I totally agree!

I'll see what we can do to make this more extensible, in theory should be low effort to fix. Give me a few days :)

**Comment by eonarheim** [comment]
@hanekoo This should be fixed in the latest alpha `excalibur@0.31.0-alpha.1327`

https://www.npmjs.com/package/excalibur/v/0.31.0-alpha.1327

Thanks again!

**Comment by hanekoo** [comment]
Happy New Year!
Thank you for the quick fix!

Generally, the 17 common buttons are enough, but it would be even better if the index could be exposed:

``` js
class GamepadButtonEvent extends GameEvent<Gamepad> {
    button: Buttons;
    index: number; // Not just when the button is unknown
    value: number;
    self: Gamepad;
    ...
}
```
For example, the Xbox Elite series controllers have additional PADDLE buttons.
If GamepadButtonEvent exposed the index, I could map the index in my program when dealing with unknown buttons.However, if the button is just unknown without the index, it would be impossible to make the mapping judgment.

**Comment by eonarheim** [comment]
@hanekoo Good point! I've made those changes https://github.com/excaliburjs/Excalibur/commit/e3d6c921c66d14cfb202a9c5fd478d2543113918

**Comment by hanekoo** [comment]
Good job! And excalibur@0.31.0-alpha.1327 tested fine.
