### ISSUE TITLE
replaying a long sound will not be muted if game is not visible

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#515]
When playing a sound with a long duration, if `sound.play()` is called more than once, each successive play of the sound (after the first one) ignores game visibility and does not mute.

**Comment by kamranayub** [comment]
Just to clarify, we are *not* trying to *prevent* multiple simultaneous plays, just respect engine visibility and keep muted on simultaneous plays.

**Comment by eonarheim** [comment]
Correct, simultaneously playing sounds is something we want. It is that subsequent plays do not respect the visibility. I think it's because the engine only keeps track the first play similar to how playing sound awaits only the first promise for completion.

**Comment by kamranayub** [comment]
This doesn't appear to be an issue with AudioTag implementation--it prevents playing when paused on the same frame.

    DOMException: The play() request was interrupted by a call to pause().

I believe the issue occurs in Web Audio because simultaneous plays are not tracked--therefore, only *currently playing track* is paused when visibility changes. When you call `play()` it creates a new web audio buffer context each time (stored on the same instance variable), thus you can have multiple buffers out at once and only the last one is paused.

There's another minor bug (I think) where inside the `hidden` event on Engine, if you call `play()` the first event handler that stops playing sounds will not catch the newly played sound so it will play. We maybe want to enhance Sound to either have a reference to engine or a flag that says whether to prevent new sounds from playing (set by `wireEngine` on visibility change events).
