### ISSUE TITLE
Image diff regression testing

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#521]
We have implemented a number of visual "test-like" demos [(/sandbox/web/tests)](https://github.com/excaliburjs/Excalibur/tree/master/sandbox/web/tests) for elements of Excalibur that are difficult to unit test. Ideally, these should be re-implemented as automatic regression tests using some sort of canvas testing framework. Options include, but are not limited to, the list below.
- https://humblesoftware.github.io/js-imagediff/
- https://github.com/platfora/Canteen

**Comment by eonarheim** [comment]
Canteen looks promising, but it is a canvas stack comparison utility... which might be okay and easier to interpret where things are different.

**Comment by eonarheim** [comment]
We should contribute back to the node-canvas project to make this happen
https://github.com/Automattic/node-canvas/issues/641

**Comment by eonarheim** [comment]
PhantomJS might be an option if we feel like fixing our problems with node-canvas is too much work (might be a good mvp?) because js-imagediff can operate in the browser canvas. Assuming that phantomjs has a canvase implementation.

Basically run our test harness in phantomjs for coverage
https://www.npmjs.com/package/jasmine-istanbul-phantom

**Comment by eonarheim** [comment]
Also maybe post the failed image regression tests to the slack room

**Comment by eonarheim** [comment]
A few things to note in this commit

1. Currently the local debugging experience is broken because I need to figure out the correct phantomjs incantation to attach vscode correctly.
2. There was a need to add 2 new feature flags to engine `ex.Engine.suppressMinimumFeatureDetection` and `ex.Engine.suppressConsoleBootMessage`
3. Additionally in this issue it was discovered that our current code coverage metric was a lie because of the way we were instrumenting our files, this commit instruments our build artifact so it is accurate.

I'm going to fix the local debugging experience before issuing a PR on this one.

**Comment by eonarheim** [comment]
An update on local debugging I found [this](https://github.com/iradul/vscode-phantomjs-debug) vscode pluging which is promising. Hopefully I get our local debug experience back with this setup.

It appears to require node v4 to be installed for it to work properly https://github.com/iradul/vscode-phantomjs-debug/issues/10 I will update our readme to reflect the node version excalibur supports as part of this issue.
