### ISSUE TITLE
Add mechanism for animated scene transition 

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#553]
### Context
I think this would help add lots of polish and atmosphere to our games and eliminate the fairly jarring switch from one scene to another that we have right now.

### Proposal
Create a new `SceneTransition` type that can interrupt and perform logic and drawing before the actual cutover to the next scene. We can implement a default `SceneTransition` and hang it off of `Scene`

Something like this.

``` typescript
class SceneTransition {
     public complete: bool = false;
     /// Indicates that the transition animation/logic
     public notifyTransitionComplete() { ... }

     public animate (ctx: Canvas2DRenderingContext, delta: number, from: Scene, to: Scene) {
         // logic and drawing

        // if the transistion is complete, notify and transition to the next scene 
        // in the engine
        if(this.complete){
           this.notifyTransitionComplete();
        }
     }

   public reset () {
      // reset scene transition state
   }
}
```

Then you could implement your own transitions, for example the black circle wipe in ala Super Mario World

``` typescript

class CircleWipeInOutTransition extends SceneTransition {
   ....
}
var game = new ex.Engine();

var myScene = new ex.Scene();
myScene.transition = new CircleWipeInOutTransition(ex.Color.Black, 200 /*ms*/);

game.add("myScene", myScene);

// at this point the Scene transition will take control and the actual scene won't
// change until notifyTransitionComplete is called.
game.goToScene("myScene"); 


```

**Comment by kamranayub** [comment]
As long as a developer can *handle* a transition, this doesn't need to be fancy, you know? We just need to provide the hooks to make it possible since a Scene could represent different things in a game--menus, levels, etc. Cool test case would be classic Zelda-style scene transitions during a level.

**Comment by eonarheim** [comment]
I suppose we probably don't need to make a separate type. We might be able to get away with a handler type approach that is overloaded less fancy :P 

Like this you think?
```typescript
// handler is called every draw, until notifyTransitionComplete is called
scene.onTransition = function(ctx, delta, fromScene, toScene) {
   // draw/animate
   if(complete){
       this.notifyTransitionComplete();
   } 
}
```

To address your question of separation, you are only going to be doing logic for drawing the transition. Are you thinking of something like? I could see that.
```typescript
class SceneTransition {
   update() {...}
   draw() {...}
} 

```

To do a Zelda-style transition you might have to manually run the draw of the 2nd scene to generate a still to animate. We probably don't want 2 scenes updating and drawing at the same time... could get messy.

**Comment by kamranayub** [comment]
Yes, since you'll probably still need to update state of the transition and we already have established a pattern that makes sense. I think a SceneTransitionHandler is fine as a separate class because you could reuse transitions then more easily (although JS is dynamic so just creating a static function and using that works too).

**Comment by eonarheim** [comment]
Yah I agree, the update/draw is consistent with our current design philosophy.

The only goofy thing would be the method signatures for update/draw would be slightly different than other things...but that's probably okay.

**Comment by kamranayub** [comment]
In order to flesh this out I was going to try implementing this in the golf sample first.

My imagined API looks like this:

- Scene.onTransition: passes next scene object and "done" callback function, overridable. Default implementation calls done() immediately. Before execution, marks protected `isTransitioning` flag for use in update/draw loops. Cannot set isTransitioning (readonly).

Deactivate can be used and will be called when transition is complete and cleanup can be done.

Lifecycle events:

- initialize (once)
- activate
- transition
- deactivate

I will try to do a POC of this in golf sample to see if it makes sense vs. having a dedicated object handle transitioning (which might be weird).

**Comment by kamranayub** [comment]
I take it back, the golf sample is a single scene so there's nothing to transition. I still think the best way to do this issue is to implement several styles of transition.

**Comment by eonarheim** [comment]
Implemented!
