### ISSUE TITLE
Add position vector to ex.Input.PointerEvent

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#612]
### Context

`ex.Input.PointerEvent` contains `x` and `y` properties because that is what the W3C spec says MouseEvent should have but to be consistent within Excalibur's API, it should just be a `pos` Vector with the same values.

Look at other events to ensure it's consistent.
### Proposal
1. `@deprecate` `x` and `y`
2. Add `pos` vector instead

This will be a breaking change when `x` and `y` are removed.

**Comment by Crizzooo** [comment]
I wanted to remove the public from X and Y so that they are not automatically created as properties on the instance, but this broke the API Docs Build. Could someone tell me if thats the intended solution? (Take in X and Y on constructor to make the `pos` vector, but not to actually use them as properties).

&& then I could use a pointer in the right direction to update the Docs/Doc Build correctly
