### ISSUE TITLE
Add back npm installation option

### ISSUE THREAD

**Issue by ShaneCourtrille** [excaliburjs/Excalibur#621]
#### Context
It looks like there use to be an npm installation path that was removed via  #391.  At that time it was true that npm meant nodejs development and bower meant client side development but that clean separation is no longer the reality.

Ember, Aurelia and Angular 2 all use npm as a distribution mechanism and now that node (and therefore npm) is shipped with Visual Studio I expect this will become the expected avenue (other then nuget obviously) for any of us who have a Microsoft background.

#### Proposal
Bring back the npm!

**Comment by kamranayub** [comment]
I can see both sides to this which makes it tough. We removed the NPM package because someone didn't realize Excalibur only ran in the browser. At the same time, some front-end frameworks are distributing through NPM primarily (which seems like it isn't right, either). Visual Studio has bower integration (including a Nuget-like UI), it works as expected, and anyone else will probably be using the bower CLI.

I'm not totally opposed to bringing back the NPM package because it doesn't seem like the community can decide whether they should stick front-end libs on bower or NPM consistently, and we know NPM is more widely integrated with tools/editors. We will just need to make it clear Ex only works in the browser and you can't use it from Node.

**Comment by eonarheim** [comment]
Is there a way to pop a warning message like "`[WARN]: Browser only library`" via npm when someone types `npm install excalibur`? Something like this may provide sufficient pause for people using it. Or perhaps a rename to something "excalibur-client"?

I'm not categorically opposed either to bringing back the NPM package, but I would want make it clear that ex is client only per #391.

**Comment by kamranayub** [comment]
After some further digging, I have some additional thoughts.

* Aurelia doesn't use bower, it uses JSPM (and npm for the CLI) because it has to do a bunch of extra configuration/dependency management on installation bower can't do
* Ember only distributes their CLI through NPM because it's powered by Node. They distribute the raw front-end framework via bower too.
* Angular2 doesn't use bower because it's not released yet. Once it is, I think they'll use it to distribute the compiled dists--currently you have to use NPM because you need to compile it and bundle it.

So, I think I will stick to the argument that Excalibur has no Node.js runtime requirements and that since we have no dependencies we should stick to using bower. These other frameworks you mention actually *do* have appropriate reasons to use NPM but they aren't distributing just the raw distributions--they compile/build/configure using NPM. In the event we create an Excalibur CLI, we could add an NPM package for it.

**Comment by ShaneCourtrille** [comment]
Ahhh sorry I should have looked before I spoke.  Yes, Bower definitely makes the most sense.  Thanks for taking the time to create such thoughtful responses.  I know what I'm doing tonight ;)

**Comment by kamranayub** [comment]
Thanks for questioning the status quo, we always appreciate feedback!

**Comment by devnewton** [comment]
Hello,

When I asked around the internet, people encourage you to drop bower in favor of npm even for frontend dependency, for example:

> Brunch does support Bower, however NPM is becoming de-facto standard for front-end packages.
> http://brunch.io/docs/using-modules

 This is quite confusing to have two dependency management system in the js world :-(

**Comment by ShaneCourtrille** [comment]
https://twitter.com/nachocoloma/status/663622545162280960

Yeah.. apparently bower is 'dead' or close to it if they can't get funding.

**Comment by kamranayub** [comment]
Wow... well, at any rate, we recently moved all our dists to a separate repository #648 so it should be easy to add a package.json and publish a new NPM package. Reopening and adding to current release milestone. What say you @eonarheim?

**Comment by eonarheim** [comment]
I agree, this is an interesting development. I think we'll want to publish
an NPM package now.
