### ISSUE TITLE
TileMaps should participate in Rigid Body Physics

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#626]
### Context

TileMap collision is currently implemented as an actor trait, which seems like undue coupling between the Actor and TileMap. It should be folded into the new collision system with a collision area implementation, since TileMaps fit the definition of a collision area 

>  A collision area is a region of space that can detect when other collision areas intersect for the purposes of colliding 2 objects in excalibur.
### Proposal

* Carve a TileMap into a set of convex polygons and create a set of collision areas for them (our collision algorithm SAT only works on convex shapes)
    https://github.com/excaliburjs/Excalibur/blob/master/src/engine/Collision/PolygonArea.ts 
* Refactor Body to not be coupled with actor, but to instead allow interfaces around these properties so that physics Body can be applied to anything
* Refactor Body to allow multiple CollisionAreas at a time or make a meta CollisionArea that is composed other collision areas (THIS WOULD BE A HUGE WIN), this will require a change in CollisionContact & DynamicTreeCollisionBroadphase to support treating multiple areas as 1 collidable object
* If CollisionPairs and CollisonContacts are generated correctly, it should just work.

**Comment by eonarheim** [comment]
This is basically a type of tessellation to convert all of the points in a TileMap into a group of convex polygons for a collision area (perhaps triangles since they always convex).

**Comment by DaVince** [comment]
I'm running into a weird collision bug between an Actor using physics and solid tiles in a TileMap. Specifically, the velocity doesn't seem to be reset so an Actor tries to force their way around the tilemap collisions until they fall through.

I imagine this issue is related, as it would probably fix the bug. Or am I better off filing a separate bug for now, considering implementation of this seems rather more advanced (not to mention it's been pushed back a lot)?
