### ISSUE TITLE
Add helper properties on body for touching and wasTouching

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/Excalibur#667]
#### Context

I would like an easy way to determine whether something was touching something else in the previous frame and is now not touching. Phaser has this functionality.

This could be enabled by adding more collision events: before, during (current one we have), after.
#### Proposal

Add `this.body.touching(actor)` and `this.body.wasTouching(actor)`

**Comment by andrewmbyrd** [comment]
I see in Body.ts and CollisionContact.ts the ways in which we determine _how_ to resolve a collision, but can you point out how Excalibur is determining _when_ a collision has occurred?

**Comment by eonarheim** [comment]
@andrewmbyrd Collision happens in 2 steps, the broadphase and the narrowphase.

The broadphase collects physics bodies that _could_ possibly collide and builds up `CollisionPair`'s, the narrowphase determines if the pairs actually contain a collision. It does this because comparing shapes n^2 across the scene is pretty expensive.

Broadphase and narrowphase
https://github.com/excaliburjs/Excalibur/blob/master/src/engine/Collision/DynamicTreeCollisionBroadphase.ts#L167

Collision pair resolution
https://github.com/excaliburjs/Excalibur/blob/master/src/engine/Collision/Pair.ts#L23

If the collision property isn't null, a collision has occured between those two bodies. This would probably be the best time to hook in and add these helpers...
