### ISSUE TITLE
Excalibur console message should automatically update for release

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/Excalibur#838]
Excalibur 0.11.0 does not show the correct label in the browser console (0.10.0 does, but this was prior to our automatic version proliferation).

### Steps to Reproduce
`npm install excalibur@0.11.0`

then 

```
var game = new ex.Engine({
    width: 800,
    height: 600
});
game.start();
```
Check the "Powered by Excalibur.js" text in the browser console.

### Expected Result
"Powered by Excalibur.js (v0.11.0)"

### Actual Result
![image](https://user-images.githubusercontent.com/675840/27014523-2742731c-4ec0-11e7-8985-61662f73285c.png)

### Environment

- browsers and versions: Google Chrome 58.0.3029.110 (64-bit), Mozilla Firefox 53.0.3 (32-bit), Microsoft Edge 40.15063.0.0
- operating system: Windows 10 Pro
- Excalibur versions: 0.11.0

**Comment by kamranayub** [comment]
Thinking about this--this gets substituted at build time, the core repo gets built, then it commit+pushes to the dist repo. I believe the way to handle this through the automation in #777 is to ensure we substitute the right version before we auto-publish to npm/Nuget. We'll probably have to do string substitution (which shouldn't be hard due to the variable name we use).

To fix it currently, @eonarheim could patch the tag and re-publish over 0.11 or issue a patch release tag (0.11.1).

**Comment by kamranayub** [comment]
Should be done by #867
