### ISSUE TITLE
Electron Fullscreen HTML Buttons don't work

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#932]
### Steps to Reproduce
See thread: https://groups.google.com/d/msg/excaliburjs/RhqzdAqhRxA/1B24OraWCgAJ

* Run Excalibur in the electron sample
* Ensure pointerscope is set to canvas
* Create HTML Buttons that are over the game canvas

### Expected Result
Electron excalibur sample using the fullscreen displaymode is not capturing HTML button clicks, currently @LePhil has a workaround to enable this
```typescript
private _addBtn(btn: Button): void {
     this.add(btn);
     this._buttons.push(btn);
}

private _toggleButtons(on: boolean): void {
    this._buttons.forEach(button => {
        button.enableCapturePointer = on;
    });
}
```

### Actual Result
HTML buttons should always just work when pointer scope is set to canvase

```typescript
var engine = new ex.Engine({
  canvasElementId: 'game',
  width: 600,
  height: 400,
  pointerScope: ex.Input.PointerScope.Canvas
});
```

**Comment by alanag13** [comment]
Would you want `ex.Input.PointerScope.Document` for this to work with HTML buttons? `Canvas` only responds to events on the canvas, which the buttons would be outside of.

**Comment by alanag13** [comment]
Okay I read the thread and have a little more context now.

I think this is happening because even if you add the button to the scene, as an Actor it is basically invisible. If you aren't giving a position or size or anything to it is probably getting added to x:0, y:0 with no width or height on the canvas. That's pretty hard to click.

The hack works because you end up adding the event listeners to the actual HTML button (instead of the Actor) like you want.

I'd have to confirm this all or maybe @LePhil can give it a try, but that's my guess for now. If you want to use HTML buttons in your game I don't think there's really a benefit to adding them to the scene -- Just wire up their events like normal, then remove them from the DOM or do `style.display = "none"` or something when you don't need them anymore. There's no need for them to be added to the scene since they aren't drawn to the canvas or interacted with in any way there.

**Comment by alanag13** [comment]
I looked at https://github.com/LePhil/ExcaliburPlayground/blob/4b0aa3b569b49843b19e081a5d5044c518497e45/game/scenes/MainMenu.ts#L149 and I'm actually more confused now -- it looks like @LePhil is using a UIActor named `Button`, not an HTML button. UIActors default to `enableCapturePointer = true`, is the problem then that in this case it seems that it needs to be set explicitly?

**Comment by alanag13** [comment]
I looked at https://github.com/LePhil/ExcaliburPlayground/blob/4b0aa3b569b49843b19e081a5d5044c518497e45/game/scenes/MainMenu.ts#L149 and I'm actually more confused now -- it looks like @LePhil is using a UIActor named `Button`, not an HTML button. UIActors default to `enableCapturePointer = true`, is the problem then that in this case it seems that it needs to be set explicitly?

**Comment by LePhil** [comment]
Ah there's some confusion going on :) 

So what I originally wanted to do was this:
Have a menu scene with some buttons (i.e. UIActors). One of these buttons opens an HTML overlay that covers the canvas. Now all clicks on the overlay should not trigger any action inside of the canvas.

I'm now unable to reproduce this on a codepen, I have to admit. My problem was that even though the HTML element was in front of the canvas, the click was still received by it and triggered actions.

I'll try to look into it again tomorrow.

**Comment by LePhil** [comment]
I can't seem to reproduce it at all anymore. I'd say close this and if it'll manifest itself again at some later point, reevaluate. Sorry for the confusion and inconvenience!

**Comment by eonarheim** [comment]
Closing, cannot reproduce
