### ISSUE TITLE
Physics Example doesn't seem to work

### ISSUE THREAD

**Issue by LePhil** [excaliburjs/Excalibur#937]
### Steps to Reproduce

Easy - try to run the provided example in the physics docs (https://excaliburjs.com/docs/api/edge/classes/_physics_.physics.html),
here as a codepen: https://codepen.io/piko_/pen/rdBBQm

### Expected Result
Some physics in action, i.e. the blocks fall down

### Actual Result
Nothing :)

### Environment
- browsers and versions: latest chrome -->
- operating system: ubuntu 
- Excalibur versions: At least 0.14, 0.15

**Comment by eonarheim** [comment]
@LePhil I have some time tonight to take a look at this

**Comment by eonarheim** [comment]
@LePhil I think the problem here is that some docs weren't updated, I've created a new codepen with the updated sample code. 

https://codepen.io/anon/pen/MVgENJ?editors=0011

The issue is that actors now default to a passive collision type, and this collision type does not participate in physics or the global physics acceleration. The reason they don't default to active collision, is so people using excalibur don't accidentally opt into something computationally expensive.

I'll update the docs sample to be correct and clarify this in our [ex.CollisionType](https://excaliburjs.com/docs/api/edge/enums/_actor_.collisiontype.html) documentation

**Comment by LePhil** [comment]
Ah very cool, thanks @eonarheim!

**Comment by jedeen** [comment]
Re-opening for tracking
