### ISSUE TITLE
PreventCollision and Active Collision Types are generating collision pairs sometimes

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#975]
### Steps to Reproduce

Add the `PreventCollision` type actor to the scene first then a `Active` collision type actor.

Possible fix https://github.com/excaliburjs/Excalibur/commit/2e0f2e7d5ed9ae8df3e9a08dc50c321f632bcdde

This appears to be the offending line of code in `Pair.ts`:

```typescript
if (actorB.collisionType === CollisionType.PreventCollision || actorB.isKilled()) { return false; }
```

### Expected Result
`PreventCollision` and `Active` collision types should never collide. 

### Actual Result
Collision pairs are being generated and postcollision events are firing erroneously.

### Environment
Excalibur @ v0.16.0

### Current Workaround
Currently this does not cause too much trouble, but it does generate pairs unecessarily no physics resoultion happens. The workaround is to inspect postcollision events before handling them.

**Comment by alanag13** [comment]
Does anyone remember the exact scenario in the last LD where we observed this problem? I'm a little confused about the possible fix because of [this line](https://github.com/excaliburjs/Excalibur/blob/2e0f2e7d5ed9ae8df3e9a08dc50c321f632bcdde/src/engine/Collision/DynamicTreeCollisionBroadphase.ts#L77) which should make it so that ActorA is never killed or set to PreventCollision. Is it possible the fix is only due to the other change that was made, [this line](https://github.com/excaliburjs/Excalibur/blob/2e0f2e7d5ed9ae8df3e9a08dc50c321f632bcdde/src/engine/Scene.ts#L644)?
