### ISSUE TITLE
Replace Excalibur promise implementation with browser implementation

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#994]
### Context
Currently we have a basic functioning custom promise implementation, but this prevents new browser features like `async`/`await` from working natively. Additionally we will get a bunch of promise features for free by switching to native promises. It may also come with a bonus of closing these #533 #365 #341

### Proposal

- [ ] Add the tsconfig native promise polyfill [option](https://www.typescriptlang.org/docs/handbook/compiler-options.html) `lib: ES2018.Promise`
- [ ] For backwards compatibility for other games, change `ex.Promise` implementation to wrap the native one.
- [ ] Replace existing methods in excalibur that use `ex.Promise` and use the native Promise returns (this will be a breaking change, unless use the `ex.Promise` wrapper, there can be no easy transition unless we rename methods)

**Comment by LoserAntbear** [comment]
Looks like we also need to add `lib: [es2015, dom]`. Because `es2018.Promise` adds `final` method to Promise interface, defined  in `es2015.promise` `PromiseConstructor`, if i understand this right. I already made this changes and also replaced all uses of `ex.Promise` with native `es6-promises` and ready to push here. But i am a bit confused with providing backwards compatibility to `ex.Promise`. Now i just added as prop `ex.Promise._nativePromise` which resolves on `ex.Promise.resolve` and rejects on `ex.Promise.reject`, but i feel it is not the way it is meant to be. :)

**Comment by LoserAntbear** [comment]
Hello again! I am sorry, bear with me. :D Could you look into this, please?

**Comment by eonarheim** [comment]
@LoserAntbear Adding `lib: [es2015, dom]` makes sense to me.

Please send a PR, as long as the new implementation of `ex.Promise` backed by the `_nativePromise` behaves in a similar way to the old one (the tests should be a good indicator) that's what we want.

**Comment by kamranayub** [comment]
You could be even more specific I think and do es2015.promise or something
like that.
